app = Application("iTunes");
tracks_in_playlist = app.currentPlaylist().tracks().map(function(track){
  return { albumArtist: track.albumArtist(),
           albumLoved: track.albumLoved(),
           albumRating: track.albumRating(),
           albumRatingKind: track.albumRatingKind(),
           artist: track.artist(),
           bitRate: track.bitRate(),
           bookmark: track.bookmark(),
           bookmarkable: track.bookmarkable(),
           bpm: track.bpm(),
           category: track.category(),
           comment: track.comment(),
           compilation: track.compilation(),
           composer: track.composer(),
           databaseID: track.databaseID(),
           dateAdded: track.dateAdded(),
           description: track.description(),
           discCount: track.discCount(),
           discNumber: track.discNumber(),
           duration: track.duration(),
           enabled: track.enabled(),
           episodeID: track.episodeID(),
           episodeNumber: track.episodeNumber(),
           eq: track.eq(),
           finish: track.finish(),
           gapless: track.gapless(),
           genre: track.genre(),
           grouping: track.grouping(),
           itunesu: track.itunesu(),
           kind: track.kind(),
           longDescription: track.longDescription(),
           loved: track.loved(),
           lyrics: track.lyrics(),
           modificationDate: track.modificationDate(),
           name: track.name(),
           playedCount: track.playedCount(),
           playedDate: track.playedDate(),
           podcast: track.podcast(),
           rating: track.rating(),
           ratingKind: track.ratingKind(),
           releaseDate: track.releaseDate(),
           sampleRate: track.sampleRate(),
           seasonNumber: track.seasonNumber(),
           shufflable: track.shufflable(),
           skippedCount: track.skippedCount(),
           skippedDate: track.skippedDate(),
           show: track.show(),
           sortAlbum: track.sortAlbum(),
           sortArtist: track.sortArtist(),
           sortAlbumArtist: track.sortAlbumArtist(),
           sortName: track.sortName(),
           sortComposer: track.sortComposer(),
           sortShow: track.sortShow(),
           size: track.size(),
           start: track.start(),
           time: track.time(),
           trackNumber: track.trackNumber(),
           unplayed: track.unplayed(),
           videoKind: track.videoKind(),
           volumeAdjustment: track.volumeAdjustment(),
           year: track.year()
         };
});
JSON.stringify(tracks_in_playlist);
